# Generated by Django 2.0.7 on 2018-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(to='doc_mgmt.User'),
        ),
    ]
