# Generated by Django 2.0.7 on 2018-07-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_mgmt', '0002_auto_20180705_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='likes',
            field=models.ManyToManyField(related_name='liked_docs', to='doc_mgmt.User'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(related_name='authored_docs', to='doc_mgmt.User'),
        ),
    ]
